apiVersion: v1
kind: Secret
metadata:
    name: ai-secret
    namespace: aiValidation
type: Opaque
data:
    MONGO_URI: bW9uZ29kYitzcnY6Ly9wcml5YW5rYWt1bWFyaTRwcV9kYl91c2VyOnByaXlhbmthMTIzQGNsdXN0ZXIwLmJ1dmh4cXUubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=
    GEMINI_API_KEY: QUl6YVN5QVEtSmIwSm1YLXFzdWR0ektITGRnOExUOWdlUXo3RGZF
