apiVersion: v1
kind: Secret
metadata:
    name: ai-secret
    namespace: aivalidation
type: Opaque
data:
    MONGO_URI: bW9uZzQGNsdXN0ZXIwLmJ1dmh4cXUubW9******
    GEMINI_API_KEY: QLl6hggh78YVN5Q******
