apiVersion: v1
kind: Service
metadata:
    name: backend-service
    namespace: aiValidation
spec:
    selector:
        app: ai-backend
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
    type: LoadBalancer
